### ISSUE TITLE
Error near  self.run() in index.js file

### ISSUE THREAD

**Issue by unagi2020** [jnutter/phantom-pdf#4]
I am getting following error ... Please help

  Using route with id:eventBadgeCreate id:create
 /home/app/node_modules/phantom-pdf/lib/index.js:25
 			 self.run();
 ^
 TypeError: Object #<Object> has no method 'run'
     at /home/app/node_modules/phantom-pdf/lib/index.js:25:10
     at Object.exports.process (/home/app/node_modules/phantom-pdf/lib/css.js:8:10)
     at /home/app/node_modules/phantom-pdf/lib/index.js:21:7
     at /home/app/node_modules/phantom-pdf/lib/dependencies.js:5:3
     at ChildProcess.exithandler (child_process.js:645:7)
     at ChildProcess.emit (events.js:98:17)
     at maybeClose (child_process.js:755:16)
     at Process.ChildProcess._handle.onexit (child_process.js:822:5)
 error: Forever detected script exited with code: 8
 error: Script restart attempt #1

**Comment by unagi2020** [comment]
Please ignore this issue. I forgot to create the instance. Sorry !!!
